//Create a collection of commanders
const commanders = {};

//Check to see if there are commanders saved



//Check to see if the user entered data
const validData = () => {
    if (document.getElementById("user-first-name").value && document.getElementById("user-birthday").value) {
        return true;
    }
    
    if (!document.getElementById("user-first-name").value) {
        // need to create a modle to show that it needs to be entered
        console.log("Please enter a commander name");
    }
    if (!document.getElementById("user-birthday").value) {
        console.log("Please enter a birthday");
    }

    return false;
}

// create a new commander
const createCommander = () => {
    
    if (validData()) {
        let userFirstName     = document.getElementById("user-first-name").value;
        let userBirthday      = document.getElementById("user-birthday").value;
        let userFavoriteColor = document.getElementById("user-favorite-color").value;
        
        //add the commander to the collection of commanders
        commanders[userFirstName] = { 
            "name"          : userFirstName,
            "birthdate"     : userBirthday,
            "favoriteColor" : userFavoriteColor
        }
        
        console.log(commanders);
        
        showCommandCenter(commanders[userFirstName]);
    }
}

const showCommandCenter = (commander) => {
    
    //hide new uers sign up
    document.getElementById("new-user-sign-up").classList.add("hidden");
    document.getElementById("h1-welcome").classList.add("hidden");
    document.getElementById("command-center").classList.remove("hidden");
    console.log(commander);

    //set commander name
    document.getElementById("commander-name").innerText = commander.name;
}



document.getElementById("btn-command").addEventListener('click', () => createCommander());

// Grid demo
const demoGridContainer = document.getElementById("demo");

const demoButtons = document.querySelectorAll(".button-container button");

function changeLayout(layout, btn) {
  demoGridContainer.classList.remove("layout-one", "layout-two", "layout-three");
  demoGridContainer.classList.add(layout);
  
  demoButtons.forEach(b => b.classList.remove("active"));
  
  btn.classList.add("active");
  console.log(layout);
}
  
let btn1 = document.getElementById("layout1");
let btn2 = document.getElementById("layout2");
let btn3 = document.getElementById("layout3");

btn1.addEventListener("click", (e) => changeLayout("layout-one", e.target));
btn2.addEventListener("click", (e) => changeLayout("layout-two", e.target));
btn3.addEventListener("click", (e) => changeLayout("layout-three", e.target));

//Demo widgets

// Get Weather for SPSCC generated by ChatGPT

async function getDailyForecast() {
  // 1) Get location (fallback if geolocation denied)
  let lat = 47.0379, lon = -122.9007; // Olympia, WA fallback
  try {
    const pos = await new Promise((res, rej) =>
      navigator.geolocation.getCurrentPosition(res, rej, {
        enableHighAccuracy: true,
        timeout: 8000
      })
    );
    lat = pos.coords.latitude;
    lon = pos.coords.longitude;
  } catch (e) {
    console.warn("Geolocation denied, using fallback.");
  }

  // 2) Get NWS points info (gives us forecast URL + city/state)
  const pointsResp = await fetch(`https://api.weather.gov/points/${lat},${lon}`);
  if (!pointsResp.ok) throw new Error("NWS /points failed");
  const points = await pointsResp.json();

  const forecastUrl = points.properties.forecast;
  const office      = points.properties.cwa;
  const city        = points.properties.relativeLocation?.properties.city;
  const state       = points.properties.relativeLocation?.properties.state;

  // 3) Get the 7-day forecast periods
  const fcResp = await fetch(forecastUrl);
  if (!fcResp.ok) throw new Error("NWS forecast failed");
  const fc = await fcResp.json();
  const periods = fc.properties.periods; // array of forecast periods

  // 4) Group periods by calendar date
  const dayMap = new Map();

  periods.forEach(p => {
    const dateStr = p.startTime.slice(0, 10); // 'YYYY-MM-DD'
    const dateObj = new Date(dateStr + "T00:00:00");
    if (!dayMap.has(dateStr)) {
      dayMap.set(dateStr, {
        dateStr,
        dateObj,
        periods: []
      });
    }
    dayMap.get(dateStr).periods.push(p);
  });

  // 5) Sort days and keep first N (e.g. next 5 days)
  const days = [...dayMap.values()]
    .sort((a, b) => a.dateObj - b.dateObj)
    .slice(0, 5)
    .map((d, idx) => {
      const today = new Date();
      today.setHours(0,0,0,0);

      const isToday = d.dateObj.getTime() === today.getTime();
      const labelBase = d.dateObj.toLocaleDateString(undefined, {
        weekday: "short",
        month: "short",
        day: "numeric"
      });

      let label;
      if (isToday) label = `Today – ${labelBase}`;
      else if (idx === 1) label = `Tomorrow – ${labelBase}`;
      else label = labelBase;

      return {
        label,
        dateObj: d.dateObj,
        periods: d.periods
      };
    });

  return { city, state, office, days };
}

// Build the slider widget in #demo-weather-content
getDailyForecast()
  .then(data => {
    const container = document.getElementById("demo-weather-content");
    if (!container) return;

    const days = data.days;
    let currentIndex = 0;

    container.innerHTML = `
      <div class="weather-widget">
        <div class="weather-header">
          <h3>Weather for ${data.city}, ${data.state}</h3>
        </div>
        <div class="weather-body">
          <button class="weather-nav prev" aria-label="Previous day">&larr;</button>
          <div class="weather-slide" aria-live="polite"></div>
          <button class="weather-nav next" aria-label="Next day">&rarr;</button>
        </div>
        <div class="weather-footer">
          <span class="weather-counter"></span>
          <span class="weather-office">Forecast office: ${data.office}</span>
        </div>
      </div>
    `;

    const slideEl   = container.querySelector(".weather-slide");
    const counterEl = container.querySelector(".weather-counter");
    const prevBtn   = container.querySelector(".weather-nav.prev");
    const nextBtn   = container.querySelector(".weather-nav.next");

    function renderDay(index) {
      const total = days.length;
      if (total === 0) {
        slideEl.innerHTML = "<p>No forecast available.</p>";
        counterEl.textContent = "";
        return;
      }

      // wrap index
      if (index < 0) index = total - 1;
      if (index >= total) index = 0;
      currentIndex = index;

      const day = days[currentIndex];

      const periodsHtml = day.periods.map(p => {
        return `
          <li class="weather-period">
            <div class="weather-period-name">${p.name}</div>
            <div class="weather-period-main">
              <span class="temp">${p.temperature}&deg;${p.temperatureUnit}</span>
              <span class="short">${p.shortForecast}</span>
            </div>
            <div class="weather-period-detail">${p.detailedForecast}</div>
            <div class="weather-period-wind">Wind: ${p.windSpeed} ${p.windDirection}</div>
          </li>
        `;
      }).join("");

      slideEl.innerHTML = `
        <h4>${day.label}</h4>
        <ul class="weather-periods">
          ${periodsHtml}
        </ul>
      `;

      counterEl.textContent = `${currentIndex + 1} / ${total}`;
    }

    prevBtn.addEventListener("click", () => renderDay(currentIndex - 1));
    nextBtn.addEventListener("click", () => renderDay(currentIndex + 1));

    // initial render
    renderDay(0);
  })
  .catch(err => {
    console.error(err);
    const div = document.getElementById("demo-weather-content");
    if (div) div.textContent = "Could not load weather data 😔";
  });





// ChatGPT Get date and type of day - count days till weekend
function formatDatePretty(date) {
  const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

  const month = monthNames[date.getMonth()];
  const dayNum = date.getDate();

  const suffix =
    (dayNum % 10 === 1 && dayNum !== 11) ? "st" :
    (dayNum % 10 === 2 && dayNum !== 12) ? "nd" :
    (dayNum % 10 === 3 && dayNum !== 13) ? "rd" :
    "th";

  return `${month} ${dayNum}${suffix}`;
}

function getDayInfo() {
  const dayNames = [
    "Sunday", "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday"
  ];

  const today = new Date();
  const dayIndex = today.getDay(); // 0-6
  const dayName = dayNames[dayIndex];
  const prettyDate = formatDatePretty(today);

  const isWeekend = (dayIndex === 0 || dayIndex === 6);
  let message;
  let progressPercent;

  if (!isWeekend) {
    // Weekday → days until Saturday
    const daysUntilWeekend = 6 - dayIndex;      // Saturday index is 6
    message = daysUntilWeekend === 1
      ? "1 day until the weekend!"
      : `${daysUntilWeekend} days until the weekend!`;

    // Progress through Mon–Fri
    // Monday (1) -> 0%, Friday (5) -> 80%
    const daysPassed = dayIndex - 1;            // Mon=0, Tue=1, ... Fri=4
    const totalDays = 5;                        // Mon–Fri window
    progressPercent = Math.max(0, Math.min(100, (daysPassed / totalDays) * 100));
  } else {
    // Weekend → days until Monday
    const daysUntilMonday = (dayIndex === 6) ? 2 : 1;
    message = daysUntilMonday === 1
      ? "1 day until Monday."
      : `${daysUntilMonday} days until Monday.`;

    // On the weekend, bar is full
    progressPercent = 100;
  }

  // Round for display
  progressPercent = Math.round(progressPercent);

  return {
    prettyDate,
    dayName,
    message,
    progressPercent
  };
}

// Render to #demo-important-content
const info = getDayInfo();
const box = document.getElementById("demo-important-content");

box.innerHTML = `
  <p style="font-size:1.2rem; margin:0;">Today</p>
  <p style="font-size:1.6rem; font-weight:700; margin:0.2rem 0;">${info.prettyDate}</p>
  <p style="font-size:0.9rem; opacity:0.8; margin:0;">${info.dayName}</p>
  <p style="margin-top:0.8rem;">${info.message}</p>

  <div class="week-progress" aria-label="Progress toward the weekend">
    <div class="week-progress-bar" style="width: ${info.progressPercent}%;"></div>
  </div>
  <p class="week-progress-label">Weekend loading: ${info.progressPercent}%</p>
`;


// Show how many days till the next holiday. 

const HOLIDAY_JSON_URL = "scripts/us-holidays.json";

function getNthWeekdayOfMonth(year, monthIndex, weekdayIndex, n) {
  // monthIndex: 0–11, weekdayIndex: 0–6 (Sun–Sat), n: 1,2,3,... or -1 for last
  if (n > 0) {
    const firstOfMonth = new Date(year, monthIndex, 1);
    const firstDay = firstOfMonth.getDay();
    const offset = (weekdayIndex - firstDay + 7) % 7;
    const day = 1 + offset + 7 * (n - 1);
    return new Date(year, monthIndex, day);
  } else {
    // last nth weekday (n = -1)
    const lastOfMonth = new Date(year, monthIndex + 1, 0); // last day of month
    const lastDay = lastOfMonth.getDay();
    const offset = (lastDay - weekdayIndex + 7) % 7;
    const day = lastOfMonth.getDate() - offset;
    return new Date(year, monthIndex, day);
  }
}

// Easter: Anonymous Gregorian algorithm (so Easter in JSON can be used too)
function getEasterSunday(year) {
  const a = year % 19;
  const b = Math.floor(year / 100);
  const c = year % 100;
  const d = Math.floor(b / 4);
  const e = b % 4;
  const f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3);
  const h = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4);
  const k = c % 4;
  const l = (32 + 2 * e + 2 * i - h - k) % 7;
  const m = Math.floor((a + 11 * h + 22 * l) / 451);
  const month = Math.floor((h + l - 7 * m + 114) / 31);   // 3=March, 4=April
  const day = ((h + l - 7 * m + 114) % 31) + 1;
  return new Date(year, month - 1, day);
}

function getHolidayDateForYear(holiday, year) {
  if (holiday.movable) {
    // Only Easter is marked movable in our JSON
    return getEasterSunday(year);
  }

  const monthIndex = (holiday.month - 1);

  if (typeof holiday.day === "number") {
    // Fixed date holiday
    return new Date(year, monthIndex, holiday.day);
  }

  if (holiday.weekday && typeof holiday.week === "number") {
    const weekdayMap = {
      "Sunday": 0, "Monday": 1, "Tuesday": 2,
      "Wednesday": 3, "Thursday": 4, "Friday": 5, "Saturday": 6
    };
    const weekdayIndex = weekdayMap[holiday.weekday];
    return getNthWeekdayOfMonth(year, monthIndex, weekdayIndex, holiday.week);
  }

  // Fallback if something is missing, just return Jan 1
  return new Date(year, 0, 1);
}

function getNextOccurrence(holiday, now) {
  const year = now.getFullYear();
  let dateThisYear = getHolidayDateForYear(holiday, year);

  // Normalize times to midnight for comparison
  const todayMid = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const holidayMid = new Date(dateThisYear.getFullYear(), dateThisYear.getMonth(), dateThisYear.getDate());

  if (holidayMid < todayMid) {
    // Already passed this year → use next year
    dateThisYear = getHolidayDateForYear(holiday, year + 1);
  }

  return dateThisYear;
}

function formatCountdown(deltaMs) {
  const msPerMinute = 60 * 1000;
  const msPerHour   = 60 * msPerMinute;
  const msPerDay    = 24 * msPerHour;

  const days  = Math.floor(deltaMs / msPerDay);
  const rem1  = deltaMs % msPerDay;
  const hours = Math.floor(rem1 / msPerHour);
  const rem2  = rem1 % msPerHour;
  const mins  = Math.floor(rem2 / msPerMinute);

  return { days, hours, mins };
}

async function initHolidayCountdown() {
  const container = document.getElementById("demo-calendar-content");
  if (!container) return;

  try {
    const res = await fetch(HOLIDAY_JSON_URL);
    if (!res.ok) throw new Error("Failed to load holidays JSON");
    const data = await res.json();
    const holidays = data.holidays || [];

    const now = new Date();

    // Build list of upcoming holiday instances (date >= today)
    const upcoming = holidays.map(h => {
      const nextDate = getNextOccurrence(h, now);
      const deltaMs = nextDate - now;
      return {
        holiday: h,
        date: nextDate,
        deltaMs
      };
    }).filter(item => item.deltaMs > 0)
      .sort((a, b) => a.date - b.date);

    if (upcoming.length === 0) {
      container.textContent = "No upcoming holidays found.";
      return;
    }

    const nextHoliday = upcoming[0];
    const following   = upcoming.slice(1); // all the rest

    const msPerDay = 24 * 60 * 60 * 1000;
    const isClose = nextHoliday.deltaMs <= 7 * msPerDay;

    const countdown = formatCountdown(nextHoliday.deltaMs);
    const daysOnlyText = `${Math.ceil(nextHoliday.deltaMs / msPerDay)} day${Math.ceil(nextHoliday.deltaMs / msPerDay) === 1 ? "" : "s"}`;

    const mainCountdownText = isClose
      ? `${countdown.days} day${countdown.days === 1 ? "" : "s"}, ${countdown.hours} hour${countdown.hours === 1 ? "" : "s"}, ${countdown.mins} minute${countdown.mins === 1 ? "" : "s"}`
      : daysOnlyText;

    const options = { weekday: "short", month: "short", day: "numeric", year: "numeric" };
    const nextDateLabel = nextHoliday.date.toLocaleDateString(undefined, options);

    // Build HTML
    let html = `
      <div class="holiday-widget">
        <h3>Next Holiday</h3>
        <div class="holiday-next">
          <p class="holiday-name">${nextHoliday.holiday.name}</p>
          <p class="holiday-date">${nextDateLabel}</p>
          <p class="holiday-countdown">In ${mainCountdownText}</p>
          <p class="holiday-description">${nextHoliday.holiday.description || ""}</p>
        </div>
    `;

    if (following.length > 0) {
      html += `<h4>Coming Up</h4><ul class="holiday-list">`;
      html += following.map(item => {
        const d = item.date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
        const daysAway = Math.ceil(item.deltaMs / msPerDay);
        return `
          <li>
            <span class="holiday-list-name">${item.holiday.name}</span>
            <span class="holiday-list-date">${d}</span>
            <span class="holiday-list-count">${daysAway} day${daysAway === 1 ? "" : "s"}</span>
          </li>
        `;
      }).join("");
      html += `</ul>`;
    }

    html += `</div>`;

    container.innerHTML = html;
  } catch (err) {
    console.error(err);
    container.textContent = "Could not load holiday countdown.";
  }
}

// Call this after the DOM is loaded
initHolidayCountdown();


// Open and close the settings side menu

//set variables 
const settingsMenu = document.getElementById("settings-menu");

//tracks if the menu is closed or open
let menuToggle = true;

//check to see if the menu is open or not.
//this allows users to click on the settings button to open and close the menu
document.getElementById("settings-menu-btn").addEventListener("click", () => {
    if (menuToggle) {
        settingsMenu.classList.add("visible", "slide-right");
        menuToggle = !menuToggle;
    } else {
        settingsMenu.classList.remove("visible");
        menuToggle = !menuToggle;
    }
});

//Close the menu from the close button in the menu
document.getElementById("menu-close").addEventListener("click", () => {
    settingsMenu.classList.remove("visible");
    menuToggle = true;
});

//Close the menu when focus is lost, ie. when user clicks off of the menu
// still working on this, does not work yet
// settingsMenu.addEventListener('blur', () => {
//     settingsMenu.classList.remove("visible");
//     menuToggle = true;
//     console.log("blur");
// });

window.onclick = function(event) {
  if (event.target == settingsMenu) {
    settingsMenu.classList.remove("visible");
    menuToggle = true;
    console.log("blur");
  }
}